# Generated by Django 5.0.2 on 2024-05-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='department',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
