# Generated by Django 5.0.2 on 2024-05-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_delete_assignment_alter_employee_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='payroll_images/'),
        ),
    ]
