# Generated by Django 5.0.2 on 2024-05-15 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20240515_2313'),
    ]

    operations = [
    ]
