# Generated by Django 5.0.2 on 2024-05-15 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_auto_20240515_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='image',
        ),
    ]
