# Generated by Django 5.0.2 on 2024-05-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_payroll_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='deleted',
        ),
    ]
